<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>ETABSModelDefinitionValidator.Rules</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\ETABSModelDefinitionValidator.Core\ETABSModelDefinitionValidator.Core.csproj" />
  </ItemGroup>

</Project>
